version: '3'

# services:
#   mysql:
#     image: mysql:latest
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"

#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mysql
#     volumes:
#       - .:/app

# volumes:
#   mysql_data:

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/db

volumes:
  sqlite_data: